server:
  port: 8086
  servlet:
    context-path: /api/anti-fraud
management:
  server:
    port: 8186
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: anti-fraud-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: password
  liquibase:
    default-schema: public
    change-log: db/changelog/db.changelog-master.yaml
    enabled: ${LIQUIBASE_ENABLED:true}
    drop-first: ${LIQUIBASE_DROP_FIRST:false}
  application:
    name: anti-fraud-app
logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka: INFO
app:
  kafka:
    topics:
      transfer:
        account: transfer.antifraud.account
        card: transfer.antifraud.card
        phone: transfer.antifraud.phone
      suspicious-transfers:
        create: suspicious-transfers.create
        update: suspicious-transfers.update
        delete: suspicious-transfers.delete
        get: suspicious-transfers.get
        get-reply: suspicious-transfers.get.reply
      audit: audit-events

